function getAfricanCountries() {
    return {
        TCD: {name:'Chad', question:'N’Djamena', map:'af'},
        EGY: {name:'Egypt', question:'Cairo', map:'af'},
        SDN: {name:'Sudan', question:'Khartoum', map:'af'},
        NER: {name:'Niger', question:'Niamey', map:'af'},
        NGA: {name:'Nigeria', question:'Abuja', map:'af'},
        COG: {name:'Republic of the Congo', question:'Brazzaville', map:'af'},
        MDG: {name:'Madagascar', question:'Antananarivo', map:'af'},
        ZAF: {name:'South Africa', question:'Pretoria (executive capital)', map:'af'},
        LSO: {name:'Lesotho', question:'Maseru', map:'af'},
        ZWE: {name:'Zimbabwe', question:'Harare', map:'af'},
        COD: {name:'Democratic Republic of the Congo', question:'Kinshasa', shortName: 'DRC', map:'af'},
        NAM: {name:'Namibia', question:'Windhoek', map:'af'},
        TGO: {name:'Togo', question:'Lome', map:'af'},
        GHA: {name:'Ghana', question:'Accra', map:'af'},
        GNQ: {name:'Equatorial Guinea', question:'Malabo', map:'af'},
        GNB: {name:'Guinea-Bissau', question:'Bissau', map:'af'},
        SLE: {name:'Sierra Leone', question:'Freetown', map:'af'},
        GMB: {name:'The Gambia', question:'Banjul', map:'af'},
        LBR: {name:'Liberia', question:'Monrovia', map:'af'},
        SEN: {name:'Senegal', question:'Dakar', map:'af'},
        KEN: {name:'Kenya', question:'Nairobi', map:'af'},
        SWZ: {name:'Swaziland', question:'Mbabane', map:'af'},
        RWA: {name:'Rwanda', question:'Kigali', map:'af'},
        BDI: {name:'Burundi', question:'Bujumbura', map:'af'},
        SOM: {name:'Somalia', question:'Mogadishu', map:'af'},
        TUN: {name:'Tunisia', question:'Tunis', map:'af'},
        CMR: {name:'Cameroon', question:'Yaounde', map:'af'},
        MAR: {name:'Morocco', question:'Rabat', map:'af'},
        ESH: {name:'Western Sahara (disputed)', question:'El Aaiún', disputed: '1', map:'af'},
        GAB: {name:'Gabon', question:'Libreville', map:'af'},
        MRT: {name:'Mauritania', question:'Nouakchott', map:'af'},
        MOZ: {name:'Mozambique', question:'Maputo', map:'af'},
        DJI: {name:'Djibouti', question:'Djibouti', map:'af'},
        MWI: {name:'Malawi', question:'Lilongwe', map:'af'},
        CAF: {name:'Central African Republic', question:'Bangui', map:'af'},
        BEN: {name:'Benin', question:'Porto-Novo', map:'af'},
        ERI: {name:'Eritrea', question:'Asmara', map:'af'},
        ETH: {name:'Ethiopia', question:'Addis Ababa', map:'af'},
        BFA: {name:'Burkina Faso', question:'Ouagadougou', map:'af'},
        CIV: {name:'Côte d’Ivoire (Ivory Coast)', question:'Yamoussoukro',shortName: 'Côte d’Ivoire', map:'af'},
        ZMB: {name:'Zambia', question:'Lusaka', map:'af'},
        AGO: {name:'Angola', question:'Luanda', map:'af'},
        BWA: {name:'Botswana', question:'Gaborone', map:'af'},
        LBY: {name:'Libya', question:'Tripoli', map:'af'},
        DZA: {name:'Algeria', question:'Algiers', map:'af'},
        MLI: {name:'Mali', question:'Bamako', map:'af'},
        GIN: {name:'Guinea', question:'Conakry', map:'af'},
        UGA: {name:'Uganda', question:'Kampala', map:'af'},
        TZA: {name:'Tanzania', question:'Dodoma (* see notes)', map:'af'},
        CPV: {name:'Cabo Verde (Cape Verde)', question:'Praia', map:'af'},
        STP: {name:'Sao Tome and Principe', question:'São Tomé', map:'af'},
        SYC: {name:'Seychelles', question:'Victoria', map:'af'},
        COM: {name:'Comoros', question:'Moroni', map:'af'},
        MUS: {name:'Mauritius', question:'Port Louis', map:'af'},
        SSD: {name:'South Sudan', question:'Juba', map:'af'}
    };
}